variables:
  a: 'pipeline yaml'

stages:
- stage: one
  displayName: one
  variables:
   - name: a
     value: 'stage yaml'

  jobs:
  - job: A
  #  variables:
  #  - name: a
  #    value: 'job yaml'
    steps:
      - bash: echo $(a)        # This will be 'job yaml'